title: Atlantic Synagogues
email: eam5hc@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eam5.github.io/atlanticsynagogues" # the base hostname & protocol for your site, e.g. http://example.com
github_username: eam5

# Build settings
#theme: minima

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: _sass

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:

  - data: 'buildings'
    template: 'building'
    name: 'idbuildings'
    dir: 'buildings'
    title: 'building_name'
    
  - data: 'building_images'
    template: 'image-gallery'
    name: 'building_name'
    dir: 'building-images'
    title: 'building_name'

  - data: 'location_images'
    template: 'locations'
    name: 'location_name'
    dir: 'locations'
    title: 'location_name'